$VERBOSE = true
require_relative 'helper'

require_relative 'test_striuct-version'
require_relative 'test_striuct-subclass-to_struct'
require_relative 'test_striuct-singleton_class-define'
require_relative 'test_striuct-subclass-class-cloning'
require_relative 'test_striuct-subclass-class-for_pairs'
require_relative 'test_striuct-subclass-class-inheritable'
require_relative 'test_striuct-subclass-class-lock'
require_relative 'test_striuct-subclass-class-methods'
require_relative 'test_striuct-subclass-class-safety_naming'
require_relative 'test_striuct-subclass-instance-adjuster'
require_relative 'test_striuct-subclass-instance-alias_member'
require_relative 'test_striuct-subclass-instance-assign'
require_relative 'test_striuct-subclass-instance-basic'
require_relative 'test_striuct-subclass-instance-cloning'
require_relative 'test_striuct-subclass-instance-default_value'
require_relative 'test_striuct-subclass-instance-freeze'
require_relative 'test_striuct-subclass-instance-functional_condition'
require_relative 'test_striuct-subclass-instance-getter_validation'
require_relative 'test_striuct-subclass-instance-hashlike'
require_relative 'test_striuct-subclass-instance-inference'
require_relative 'test_striuct-subclass-instance-keyvalidatable'
require_relative 'test_striuct-subclass-instance-lock'
require_relative 'test_striuct-subclass-instance-specific_conditions'
