language: ruby

rvm:
  - ruby-head
  - 2.5
  - 2.4
  - rbx-3
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby-head

before_install:
  - gem install bundler
