require 'optionalargument'

require_relative 'attributes'
require_relative 'inner'
require_relative 'names'
require_relative 'predicate'
require_relative 'copy'
require_relative 'fix'
require_relative 'length'
require_relative 'to_struct'
require_relative 'constructor'
require_relative 'enum'
require_relative 'default'
require_relative 'adjustment'
require_relative 'macro'
require_relative 'conflict_management'
require_relative 'validation'
