# https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions
name: Lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request: null # This enables to run on each PRs
jobs:
  rubocop:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # selfup { "regex": "\\d[^']+", "script": "ruby -e 'puts RUBY_VERSION'" }
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake rubocop
