name: Update flake.lock and CI dependencies
on:
  pull_request:
    paths:
      - '.github/workflows/update-nixpkgs-and-versions-in-ci.yml'
  schedule:
    # Every Monday 10:17 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '17 1 * * 1'
  workflow_dispatch:

jobs:
  update-nixpkgs:
    uses: kachick/anylang-template/.github/workflows/reusable-update-nixpkgs-and-versions-in-ci.yml@2413fce002263e6675ce084da251be0dbbe2a8fc
    if: (github.event.sender.login == 'kachick') || (github.event_name != 'pull_request')
    with:
      dry-run: ${{ github.event_name == 'pull_request' }}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
